/* automatically generated by rust-bindgen 0.68.1 */

pub type wchar_t = ::std::os::raw::c_int;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::std::os::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}
extern "C" {
    pub fn run_powersasa(
        area_per_atom: *mut f32,
        volume_per_atom: *mut f32,
        cb_crd: ::std::option::Option<
            unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void, arg2: usize) -> *mut f32,
        >,
        cb_vdw: ::std::option::Option<
            unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void, arg2: usize) -> f32,
        >,
        context_crd: *mut ::std::os::raw::c_void,
        context_vdw: *mut ::std::os::raw::c_void,
        num: usize,
    );
}
