[package]
name = "molar_molfile"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
ascii.workspace = true
anyhow.workspace = true

[build-dependencies]
cmake.workspace = true