/* automatically generated by rust-bindgen 0.66.1 */

pub type real = f32;
#[doc = " \\libinternal \\brief\n Legacy symbol table entry as linked list."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_symbuf {
    #[doc = "! Number of entries in this item"]
    pub bufsize: ::std::os::raw::c_int,
    #[doc = "! Storage for strings in this item."]
    pub buf: *mut *mut ::std::os::raw::c_char,
    #[doc = "! Next item in linked list."]
    pub next: *mut t_symbuf,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_symtab {
    #[doc = "! Total number of entries stored."]
    pub nr: ::std::os::raw::c_int,
    #[doc = "! First item in linked list of storage elements."]
    pub symbuf: *mut t_symbuf,
}
pub const ParticleType_Atom: ParticleType = 0;
pub const ParticleType_Nucleus: ParticleType = 1;
pub const ParticleType_Shell: ParticleType = 2;
pub const ParticleType_Bond: ParticleType = 3;
pub const ParticleType_VSite: ParticleType = 4;
pub const ParticleType_Count: ParticleType = 5;
pub type ParticleType = ::std::os::raw::c_int;
pub const PdbRecordType_Atom: PdbRecordType = 0;
pub const PdbRecordType_Hetatm: PdbRecordType = 1;
pub const PdbRecordType_Anisou: PdbRecordType = 2;
pub const PdbRecordType_Cryst1: PdbRecordType = 3;
pub const PdbRecordType_Compound: PdbRecordType = 4;
pub const PdbRecordType_Model: PdbRecordType = 5;
pub const PdbRecordType_EndModel: PdbRecordType = 6;
pub const PdbRecordType_Ter: PdbRecordType = 7;
pub const PdbRecordType_Header: PdbRecordType = 8;
pub const PdbRecordType_Title: PdbRecordType = 9;
pub const PdbRecordType_Remark: PdbRecordType = 10;
pub const PdbRecordType_Conect: PdbRecordType = 11;
pub const PdbRecordType_Count: PdbRecordType = 12;
pub type PdbRecordType = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_atom {
    pub m: real,
    pub q: real,
    pub mB: real,
    pub qB: real,
    pub type_: ::std::os::raw::c_ushort,
    pub typeB: ::std::os::raw::c_ushort,
    pub ptype: ParticleType,
    pub resind: ::std::os::raw::c_int,
    pub atomnumber: ::std::os::raw::c_int,
    pub elem: [::std::os::raw::c_char; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_resinfo {
    pub name: *mut *mut ::std::os::raw::c_char,
    pub nr: ::std::os::raw::c_int,
    pub ic: ::std::os::raw::c_uchar,
    pub chainnum: ::std::os::raw::c_int,
    pub chainid: ::std::os::raw::c_char,
    pub rtp: *mut *mut ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_pdbinfo {
    pub type_: PdbRecordType,
    pub atomnr: ::std::os::raw::c_int,
    pub altloc: ::std::os::raw::c_char,
    pub atomnm: [::std::os::raw::c_char; 6usize],
    pub occup: real,
    pub bfac: real,
    pub bAnisotropic: bool,
    pub uij: [::std::os::raw::c_int; 6usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_atoms {
    pub nr: ::std::os::raw::c_int,
    pub atom: *mut t_atom,
    pub atomname: *mut *mut *mut ::std::os::raw::c_char,
    pub atomtype: *mut *mut *mut ::std::os::raw::c_char,
    pub atomtypeB: *mut *mut *mut ::std::os::raw::c_char,
    pub nres: ::std::os::raw::c_int,
    pub resinfo: *mut t_resinfo,
    pub pdbinfo: *mut t_pdbinfo,
    pub haveMass: bool,
    pub haveCharge: bool,
    pub haveType: bool,
    pub haveBState: bool,
    pub havePdbInfo: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_block {
    pub nr: ::std::os::raw::c_int,
    pub index: *mut ::std::os::raw::c_int,
    pub nalloc_index: ::std::os::raw::c_int,
}
pub type t_iatom = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub union t_iparams {
    pub bham: t_iparams__bindgen_ty_1,
    pub harmonic: t_iparams__bindgen_ty_2,
    pub linangle: t_iparams__bindgen_ty_3,
    pub restraint: t_iparams__bindgen_ty_4,
    pub cubic: t_iparams__bindgen_ty_5,
    pub fene: t_iparams__bindgen_ty_6,
    pub cross_bb: t_iparams__bindgen_ty_7,
    pub cross_ba: t_iparams__bindgen_ty_8,
    pub u_b: t_iparams__bindgen_ty_9,
    pub qangle: t_iparams__bindgen_ty_10,
    pub polarize: t_iparams__bindgen_ty_11,
    pub anharm_polarize: t_iparams__bindgen_ty_12,
    pub wpol: t_iparams__bindgen_ty_13,
    pub thole: t_iparams__bindgen_ty_14,
    pub lj: t_iparams__bindgen_ty_15,
    pub lj14: t_iparams__bindgen_ty_16,
    pub ljc14: t_iparams__bindgen_ty_17,
    pub ljcnb: t_iparams__bindgen_ty_18,
    pub pdihs: t_iparams__bindgen_ty_19,
    pub constr: t_iparams__bindgen_ty_20,
    pub settle: t_iparams__bindgen_ty_21,
    pub morse: t_iparams__bindgen_ty_22,
    pub posres: t_iparams__bindgen_ty_23,
    pub fbposres: t_iparams__bindgen_ty_24,
    pub rbdihs: t_iparams__bindgen_ty_25,
    pub cbtdihs: t_iparams__bindgen_ty_26,
    pub vsite: t_iparams__bindgen_ty_27,
    pub vsiten: t_iparams__bindgen_ty_28,
    pub disres: t_iparams__bindgen_ty_29,
    pub dihres: t_iparams__bindgen_ty_30,
    pub orires: t_iparams__bindgen_ty_31,
    pub tab: t_iparams__bindgen_ty_32,
    pub cmap: t_iparams__bindgen_ty_33,
    pub generic: t_iparams__bindgen_ty_34,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_1 {
    pub a: real,
    pub b: real,
    pub c: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_2 {
    pub rA: real,
    pub krA: real,
    pub rB: real,
    pub krB: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_3 {
    pub klinA: real,
    pub aA: real,
    pub klinB: real,
    pub aB: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_4 {
    pub lowA: real,
    pub up1A: real,
    pub up2A: real,
    pub kA: real,
    pub lowB: real,
    pub up1B: real,
    pub up2B: real,
    pub kB: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_5 {
    pub b0: real,
    pub kb: real,
    pub kcub: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_6 {
    pub bm: real,
    pub kb: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_7 {
    pub r1e: real,
    pub r2e: real,
    pub krr: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_8 {
    pub r1e: real,
    pub r2e: real,
    pub r3e: real,
    pub krt: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_9 {
    pub thetaA: real,
    pub kthetaA: real,
    pub r13A: real,
    pub kUBA: real,
    pub thetaB: real,
    pub kthetaB: real,
    pub r13B: real,
    pub kUBB: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_10 {
    pub theta: real,
    pub c: [real; 5usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_11 {
    pub alpha: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_12 {
    pub alpha: real,
    pub drcut: real,
    pub khyp: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_13 {
    pub al_x: real,
    pub al_y: real,
    pub al_z: real,
    pub rOH: real,
    pub rHH: real,
    pub rOD: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_14 {
    pub a: real,
    pub alpha1: real,
    pub alpha2: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_15 {
    pub c6: real,
    pub c12: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_16 {
    pub c6A: real,
    pub c12A: real,
    pub c6B: real,
    pub c12B: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_17 {
    pub fqq: real,
    pub qi: real,
    pub qj: real,
    pub c6: real,
    pub c12: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_18 {
    pub qi: real,
    pub qj: real,
    pub c6: real,
    pub c12: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_19 {
    pub phiA: real,
    pub cpA: real,
    pub mult: ::std::os::raw::c_int,
    pub phiB: real,
    pub cpB: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_20 {
    pub dA: real,
    pub dB: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_21 {
    pub doh: real,
    pub dhh: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_22 {
    pub b0A: real,
    pub cbA: real,
    pub betaA: real,
    pub b0B: real,
    pub cbB: real,
    pub betaB: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_23 {
    pub pos0A: [real; 3usize],
    pub fcA: [real; 3usize],
    pub pos0B: [real; 3usize],
    pub fcB: [real; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_24 {
    pub pos0: [real; 3usize],
    pub r: real,
    pub k: real,
    pub geom: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_25 {
    pub rbcA: [real; 6usize],
    pub rbcB: [real; 6usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_26 {
    pub cbtcA: [real; 6usize],
    pub cbtcB: [real; 6usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_27 {
    pub a: real,
    pub b: real,
    pub c: real,
    pub d: real,
    pub e: real,
    pub f: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_28 {
    pub n: ::std::os::raw::c_int,
    pub a: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_29 {
    pub low: real,
    pub up1: real,
    pub up2: real,
    pub kfac: real,
    pub type_: ::std::os::raw::c_int,
    pub label: ::std::os::raw::c_int,
    pub npair: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_30 {
    pub phiA: real,
    pub dphiA: real,
    pub kfacA: real,
    pub phiB: real,
    pub dphiB: real,
    pub kfacB: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_31 {
    pub ex: ::std::os::raw::c_int,
    pub power: ::std::os::raw::c_int,
    pub label: ::std::os::raw::c_int,
    pub c: real,
    pub obs: real,
    pub kfac: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_32 {
    pub table: ::std::os::raw::c_int,
    pub kA: real,
    pub kB: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_33 {
    pub cmapA: ::std::os::raw::c_int,
    pub cmapB: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_34 {
    pub buf: [real; 12usize],
}
pub type t_functype = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_ilist {
    pub nr: ::std::os::raw::c_int,
    pub iatoms: *mut t_iatom,
    pub nalloc: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_idef {
    pub ntypes: ::std::os::raw::c_int,
    pub atnr: ::std::os::raw::c_int,
    pub functype: *mut t_functype,
    pub iparams: *mut t_iparams,
    pub fudgeQQ: real,
    pub iparams_posres: *mut t_iparams,
    pub iparams_fbposres: *mut t_iparams,
    pub il: [t_ilist; 94usize],
    pub ilsort: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_topology {
    pub name: *mut *mut ::std::os::raw::c_char,
    pub idef: t_idef,
    pub atoms: t_atoms,
    pub mols: t_block,
    pub bIntermolecularInteractions: bool,
    pub symtab: t_symtab,
}
