/* automatically generated by rust-bindgen 0.70.1 */

pub const F_OK: u32 = 0;
pub const F_ULOCK: u32 = 0;
pub const F_LOCK: u32 = 1;
pub const F_TLOCK: u32 = 2;
pub const F_TEST: u32 = 3;
pub type real = f32;
#[repr(C)]
#[repr(align(8))]
pub struct t_inputrec {
    pub _bindgen_opaque_blob: [u64; 106usize],
}
extern "C" {
    #[link_name = "\u{1}_ZN10t_inputrecC1Ev"]
    pub fn t_inputrec_t_inputrec(this: *mut t_inputrec);
}
extern "C" {
    #[link_name = "\u{1}_ZN10t_inputrecD1Ev"]
    pub fn t_inputrec_t_inputrec_destructor(this: *mut t_inputrec);
}
impl t_inputrec {
    #[inline]
    pub unsafe fn new() -> Self {
        let mut __bindgen_tmp = ::std::mem::MaybeUninit::uninit();
        t_inputrec_t_inputrec(__bindgen_tmp.as_mut_ptr());
        __bindgen_tmp.assume_init()
    }
    #[inline]
    pub unsafe fn destruct(&mut self) {
        t_inputrec_t_inputrec_destructor(self)
    }
}
#[doc = " \\brief The microstate of the system\n\n The global state will contain complete data for all used entries.\n The local state with domain decomposition will have partial entries\n for which \\p stateEntryIsAtomProperty() is true. Some entries that\n are used in the global state might not be present in the local state.\n \\todo Move pure observables history to ObservablesHistory."]
#[repr(C)]
#[repr(align(8))]
pub struct t_state {
    pub _bindgen_opaque_blob: [u64; 104usize],
}
extern "C" {
    #[link_name = "\u{1}_ZN7t_stateC1Ev"]
    pub fn t_state_t_state(this: *mut t_state);
}
impl t_state {
    #[inline]
    pub unsafe fn new() -> Self {
        let mut __bindgen_tmp = ::std::mem::MaybeUninit::uninit();
        t_state_t_state(__bindgen_tmp.as_mut_ptr());
        __bindgen_tmp.assume_init()
    }
}
#[doc = " \\libinternal \\brief\n Legacy symbol table entry as linked list."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_symbuf {
    #[doc = "! Number of entries in this item"]
    pub bufsize: ::std::os::raw::c_int,
    #[doc = "! Storage for strings in this item."]
    pub buf: *mut *mut ::std::os::raw::c_char,
    #[doc = "! Next item in linked list."]
    pub next: *mut t_symbuf,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_symtab {
    #[doc = "! Total number of entries stored."]
    pub nr: ::std::os::raw::c_int,
    #[doc = "! First item in linked list of storage elements."]
    pub symbuf: *mut t_symbuf,
}
pub const ParticleType_Atom: ParticleType = 0;
pub const ParticleType_Nucleus: ParticleType = 1;
pub const ParticleType_Shell: ParticleType = 2;
pub const ParticleType_Bond: ParticleType = 3;
pub const ParticleType_VSite: ParticleType = 4;
pub const ParticleType_Count: ParticleType = 5;
pub type ParticleType = ::std::os::raw::c_int;
pub const PdbRecordType_Atom: PdbRecordType = 0;
pub const PdbRecordType_Hetatm: PdbRecordType = 1;
pub const PdbRecordType_Anisou: PdbRecordType = 2;
pub const PdbRecordType_Cryst1: PdbRecordType = 3;
pub const PdbRecordType_Compound: PdbRecordType = 4;
pub const PdbRecordType_Model: PdbRecordType = 5;
pub const PdbRecordType_EndModel: PdbRecordType = 6;
pub const PdbRecordType_Ter: PdbRecordType = 7;
pub const PdbRecordType_Header: PdbRecordType = 8;
pub const PdbRecordType_Title: PdbRecordType = 9;
pub const PdbRecordType_Remark: PdbRecordType = 10;
pub const PdbRecordType_Conect: PdbRecordType = 11;
pub const PdbRecordType_Count: PdbRecordType = 12;
pub type PdbRecordType = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_atom {
    pub m: real,
    pub q: real,
    pub mB: real,
    pub qB: real,
    pub type_: ::std::os::raw::c_ushort,
    pub typeB: ::std::os::raw::c_ushort,
    pub ptype: ParticleType,
    pub resind: ::std::os::raw::c_int,
    pub atomnumber: ::std::os::raw::c_int,
    pub elem: [::std::os::raw::c_char; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_resinfo {
    pub name: *mut *mut ::std::os::raw::c_char,
    pub nr: ::std::os::raw::c_int,
    pub ic: ::std::os::raw::c_uchar,
    pub chainnum: ::std::os::raw::c_int,
    pub chainid: ::std::os::raw::c_char,
    pub rtp: *mut *mut ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_pdbinfo {
    pub type_: PdbRecordType,
    pub atomnr: ::std::os::raw::c_int,
    pub altloc: ::std::os::raw::c_char,
    pub atomnm: [::std::os::raw::c_char; 6usize],
    pub occup: real,
    pub bfac: real,
    pub bAnisotropic: bool,
    pub uij: [::std::os::raw::c_int; 6usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_atoms {
    pub nr: ::std::os::raw::c_int,
    pub atom: *mut t_atom,
    pub atomname: *mut *mut *mut ::std::os::raw::c_char,
    pub atomtype: *mut *mut *mut ::std::os::raw::c_char,
    pub atomtypeB: *mut *mut *mut ::std::os::raw::c_char,
    pub nres: ::std::os::raw::c_int,
    pub resinfo: *mut t_resinfo,
    pub pdbinfo: *mut t_pdbinfo,
    pub haveMass: bool,
    pub haveCharge: bool,
    pub haveType: bool,
    pub haveBState: bool,
    pub havePdbInfo: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_block {
    pub nr: ::std::os::raw::c_int,
    pub index: *mut ::std::os::raw::c_int,
    pub nalloc_index: ::std::os::raw::c_int,
}
pub type t_iatom = ::std::os::raw::c_int;
pub const F_BONDS: _bindgen_ty_62 = 0;
pub const F_G96BONDS: _bindgen_ty_62 = 1;
pub const F_MORSE: _bindgen_ty_62 = 2;
pub const F_CUBICBONDS: _bindgen_ty_62 = 3;
pub const F_CONNBONDS: _bindgen_ty_62 = 4;
pub const F_HARMONIC: _bindgen_ty_62 = 5;
pub const F_FENEBONDS: _bindgen_ty_62 = 6;
pub const F_TABBONDS: _bindgen_ty_62 = 7;
pub const F_TABBONDSNC: _bindgen_ty_62 = 8;
pub const F_RESTRBONDS: _bindgen_ty_62 = 9;
pub const F_ANGLES: _bindgen_ty_62 = 10;
pub const F_G96ANGLES: _bindgen_ty_62 = 11;
pub const F_RESTRANGLES: _bindgen_ty_62 = 12;
pub const F_LINEAR_ANGLES: _bindgen_ty_62 = 13;
pub const F_CROSS_BOND_BONDS: _bindgen_ty_62 = 14;
pub const F_CROSS_BOND_ANGLES: _bindgen_ty_62 = 15;
pub const F_UREY_BRADLEY: _bindgen_ty_62 = 16;
pub const F_QUARTIC_ANGLES: _bindgen_ty_62 = 17;
pub const F_TABANGLES: _bindgen_ty_62 = 18;
pub const F_PDIHS: _bindgen_ty_62 = 19;
pub const F_RBDIHS: _bindgen_ty_62 = 20;
pub const F_RESTRDIHS: _bindgen_ty_62 = 21;
pub const F_CBTDIHS: _bindgen_ty_62 = 22;
pub const F_FOURDIHS: _bindgen_ty_62 = 23;
pub const F_IDIHS: _bindgen_ty_62 = 24;
pub const F_PIDIHS: _bindgen_ty_62 = 25;
pub const F_TABDIHS: _bindgen_ty_62 = 26;
pub const F_CMAP: _bindgen_ty_62 = 27;
pub const F_GB12_NOLONGERUSED: _bindgen_ty_62 = 28;
pub const F_GB13_NOLONGERUSED: _bindgen_ty_62 = 29;
pub const F_GB14_NOLONGERUSED: _bindgen_ty_62 = 30;
pub const F_GBPOL_NOLONGERUSED: _bindgen_ty_62 = 31;
pub const F_NPSOLVATION_NOLONGERUSED: _bindgen_ty_62 = 32;
pub const F_LJ14: _bindgen_ty_62 = 33;
pub const F_COUL14: _bindgen_ty_62 = 34;
pub const F_LJC14_Q: _bindgen_ty_62 = 35;
pub const F_LJC_PAIRS_NB: _bindgen_ty_62 = 36;
pub const F_LJ: _bindgen_ty_62 = 37;
pub const F_BHAM: _bindgen_ty_62 = 38;
pub const F_LJ_LR_NOLONGERUSED: _bindgen_ty_62 = 39;
pub const F_BHAM_LR_NOLONGERUSED: _bindgen_ty_62 = 40;
pub const F_DISPCORR: _bindgen_ty_62 = 41;
pub const F_COUL_SR: _bindgen_ty_62 = 42;
pub const F_COUL_LR_NOLONGERUSED: _bindgen_ty_62 = 43;
pub const F_RF_EXCL: _bindgen_ty_62 = 44;
pub const F_COUL_RECIP: _bindgen_ty_62 = 45;
pub const F_LJ_RECIP: _bindgen_ty_62 = 46;
pub const F_DPD: _bindgen_ty_62 = 47;
pub const F_POLARIZATION: _bindgen_ty_62 = 48;
pub const F_WATER_POL: _bindgen_ty_62 = 49;
pub const F_THOLE_POL: _bindgen_ty_62 = 50;
pub const F_ANHARM_POL: _bindgen_ty_62 = 51;
pub const F_POSRES: _bindgen_ty_62 = 52;
pub const F_FBPOSRES: _bindgen_ty_62 = 53;
pub const F_DISRES: _bindgen_ty_62 = 54;
pub const F_DISRESVIOL: _bindgen_ty_62 = 55;
pub const F_ORIRES: _bindgen_ty_62 = 56;
pub const F_ORIRESDEV: _bindgen_ty_62 = 57;
pub const F_ANGRES: _bindgen_ty_62 = 58;
pub const F_ANGRESZ: _bindgen_ty_62 = 59;
pub const F_DIHRES: _bindgen_ty_62 = 60;
pub const F_DIHRESVIOL: _bindgen_ty_62 = 61;
pub const F_CONSTR: _bindgen_ty_62 = 62;
pub const F_CONSTRNC: _bindgen_ty_62 = 63;
pub const F_SETTLE: _bindgen_ty_62 = 64;
pub const F_VSITE1: _bindgen_ty_62 = 65;
pub const F_VSITE2: _bindgen_ty_62 = 66;
pub const F_VSITE2FD: _bindgen_ty_62 = 67;
pub const F_VSITE3: _bindgen_ty_62 = 68;
pub const F_VSITE3FD: _bindgen_ty_62 = 69;
pub const F_VSITE3FAD: _bindgen_ty_62 = 70;
pub const F_VSITE3OUT: _bindgen_ty_62 = 71;
pub const F_VSITE4FD: _bindgen_ty_62 = 72;
pub const F_VSITE4FDN: _bindgen_ty_62 = 73;
pub const F_VSITEN: _bindgen_ty_62 = 74;
pub const F_COM_PULL: _bindgen_ty_62 = 75;
pub const F_DENSITYFITTING: _bindgen_ty_62 = 76;
pub const F_EQM: _bindgen_ty_62 = 77;
pub const F_EPOT: _bindgen_ty_62 = 78;
pub const F_EKIN: _bindgen_ty_62 = 79;
pub const F_ETOT: _bindgen_ty_62 = 80;
pub const F_ECONSERVED: _bindgen_ty_62 = 81;
pub const F_TEMP: _bindgen_ty_62 = 82;
pub const F_VTEMP_NOLONGERUSED: _bindgen_ty_62 = 83;
pub const F_PDISPCORR: _bindgen_ty_62 = 84;
pub const F_PRES: _bindgen_ty_62 = 85;
pub const F_DVDL_CONSTR: _bindgen_ty_62 = 86;
pub const F_DVDL: _bindgen_ty_62 = 87;
pub const F_DKDL: _bindgen_ty_62 = 88;
pub const F_DVDL_COUL: _bindgen_ty_62 = 89;
pub const F_DVDL_VDW: _bindgen_ty_62 = 90;
pub const F_DVDL_BONDED: _bindgen_ty_62 = 91;
pub const F_DVDL_RESTRAINT: _bindgen_ty_62 = 92;
pub const F_DVDL_TEMPERATURE: _bindgen_ty_62 = 93;
pub const F_NRE: _bindgen_ty_62 = 94;
pub type _bindgen_ty_62 = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub union t_iparams {
    pub bham: t_iparams__bindgen_ty_1,
    pub harmonic: t_iparams__bindgen_ty_2,
    pub linangle: t_iparams__bindgen_ty_3,
    pub restraint: t_iparams__bindgen_ty_4,
    pub cubic: t_iparams__bindgen_ty_5,
    pub fene: t_iparams__bindgen_ty_6,
    pub cross_bb: t_iparams__bindgen_ty_7,
    pub cross_ba: t_iparams__bindgen_ty_8,
    pub u_b: t_iparams__bindgen_ty_9,
    pub qangle: t_iparams__bindgen_ty_10,
    pub polarize: t_iparams__bindgen_ty_11,
    pub anharm_polarize: t_iparams__bindgen_ty_12,
    pub wpol: t_iparams__bindgen_ty_13,
    pub thole: t_iparams__bindgen_ty_14,
    pub lj: t_iparams__bindgen_ty_15,
    pub lj14: t_iparams__bindgen_ty_16,
    pub ljc14: t_iparams__bindgen_ty_17,
    pub ljcnb: t_iparams__bindgen_ty_18,
    pub pdihs: t_iparams__bindgen_ty_19,
    pub constr: t_iparams__bindgen_ty_20,
    pub settle: t_iparams__bindgen_ty_21,
    pub morse: t_iparams__bindgen_ty_22,
    pub posres: t_iparams__bindgen_ty_23,
    pub fbposres: t_iparams__bindgen_ty_24,
    pub rbdihs: t_iparams__bindgen_ty_25,
    pub cbtdihs: t_iparams__bindgen_ty_26,
    pub vsite: t_iparams__bindgen_ty_27,
    pub vsiten: t_iparams__bindgen_ty_28,
    pub disres: t_iparams__bindgen_ty_29,
    pub dihres: t_iparams__bindgen_ty_30,
    pub orires: t_iparams__bindgen_ty_31,
    pub tab: t_iparams__bindgen_ty_32,
    pub cmap: t_iparams__bindgen_ty_33,
    pub generic: t_iparams__bindgen_ty_34,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_1 {
    pub a: real,
    pub b: real,
    pub c: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_2 {
    pub rA: real,
    pub krA: real,
    pub rB: real,
    pub krB: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_3 {
    pub klinA: real,
    pub aA: real,
    pub klinB: real,
    pub aB: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_4 {
    pub lowA: real,
    pub up1A: real,
    pub up2A: real,
    pub kA: real,
    pub lowB: real,
    pub up1B: real,
    pub up2B: real,
    pub kB: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_5 {
    pub b0: real,
    pub kb: real,
    pub kcub: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_6 {
    pub bm: real,
    pub kb: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_7 {
    pub r1e: real,
    pub r2e: real,
    pub krr: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_8 {
    pub r1e: real,
    pub r2e: real,
    pub r3e: real,
    pub krt: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_9 {
    pub thetaA: real,
    pub kthetaA: real,
    pub r13A: real,
    pub kUBA: real,
    pub thetaB: real,
    pub kthetaB: real,
    pub r13B: real,
    pub kUBB: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_10 {
    pub theta: real,
    pub c: [real; 5usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_11 {
    pub alpha: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_12 {
    pub alpha: real,
    pub drcut: real,
    pub khyp: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_13 {
    pub al_x: real,
    pub al_y: real,
    pub al_z: real,
    pub rOH: real,
    pub rHH: real,
    pub rOD: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_14 {
    pub a: real,
    pub alpha1: real,
    pub alpha2: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_15 {
    pub c6: real,
    pub c12: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_16 {
    pub c6A: real,
    pub c12A: real,
    pub c6B: real,
    pub c12B: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_17 {
    pub fqq: real,
    pub qi: real,
    pub qj: real,
    pub c6: real,
    pub c12: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_18 {
    pub qi: real,
    pub qj: real,
    pub c6: real,
    pub c12: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_19 {
    pub phiA: real,
    pub cpA: real,
    pub mult: ::std::os::raw::c_int,
    pub phiB: real,
    pub cpB: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_20 {
    pub dA: real,
    pub dB: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_21 {
    pub doh: real,
    pub dhh: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_22 {
    pub b0A: real,
    pub cbA: real,
    pub betaA: real,
    pub b0B: real,
    pub cbB: real,
    pub betaB: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_23 {
    pub pos0A: [real; 3usize],
    pub fcA: [real; 3usize],
    pub pos0B: [real; 3usize],
    pub fcB: [real; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_24 {
    pub pos0: [real; 3usize],
    pub r: real,
    pub k: real,
    pub geom: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_25 {
    pub rbcA: [real; 6usize],
    pub rbcB: [real; 6usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_26 {
    pub cbtcA: [real; 6usize],
    pub cbtcB: [real; 6usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_27 {
    pub a: real,
    pub b: real,
    pub c: real,
    pub d: real,
    pub e: real,
    pub f: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_28 {
    pub n: ::std::os::raw::c_int,
    pub a: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_29 {
    pub low: real,
    pub up1: real,
    pub up2: real,
    pub kfac: real,
    pub type_: ::std::os::raw::c_int,
    pub label: ::std::os::raw::c_int,
    pub npair: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_30 {
    pub phiA: real,
    pub dphiA: real,
    pub kfacA: real,
    pub phiB: real,
    pub dphiB: real,
    pub kfacB: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_31 {
    pub ex: ::std::os::raw::c_int,
    pub power: ::std::os::raw::c_int,
    pub label: ::std::os::raw::c_int,
    pub c: real,
    pub obs: real,
    pub kfac: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_32 {
    pub table: ::std::os::raw::c_int,
    pub kA: real,
    pub kB: real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_33 {
    pub cmapA: ::std::os::raw::c_int,
    pub cmapB: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_iparams__bindgen_ty_34 {
    pub buf: [real; 12usize],
}
pub type t_functype = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_ilist {
    pub nr: ::std::os::raw::c_int,
    pub iatoms: *mut t_iatom,
    pub nalloc: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_idef {
    pub ntypes: ::std::os::raw::c_int,
    pub atnr: ::std::os::raw::c_int,
    pub functype: *mut t_functype,
    pub iparams: *mut t_iparams,
    pub fudgeQQ: real,
    pub iparams_posres: *mut t_iparams,
    pub iparams_fbposres: *mut t_iparams,
    pub il: [t_ilist; 94usize],
    pub ilsort: ::std::os::raw::c_int,
}
#[repr(C)]
#[repr(align(8))]
pub struct gmx_mtop_t {
    pub _bindgen_opaque_blob: [u64; 96usize],
}
extern "C" {
    #[doc = " \\brief Finalize this data structure.\n\n Should be called after generating or reading mtop, to set some compute\n intesive variables to avoid N^2 operations later on.\n\n \\todo Move into a builder class, once available."]
    #[link_name = "\u{1}_ZN10gmx_mtop_t8finalizeEv"]
    pub fn gmx_mtop_t_finalize(this: *mut gmx_mtop_t);
}
extern "C" {
    #[link_name = "\u{1}_ZN10gmx_mtop_tC1Ev"]
    pub fn gmx_mtop_t_gmx_mtop_t(this: *mut gmx_mtop_t);
}
extern "C" {
    #[link_name = "\u{1}_ZN10gmx_mtop_tD1Ev"]
    pub fn gmx_mtop_t_gmx_mtop_t_destructor(this: *mut gmx_mtop_t);
}
impl gmx_mtop_t {
    #[inline]
    pub unsafe fn finalize(&mut self) {
        gmx_mtop_t_finalize(self)
    }
    #[inline]
    pub unsafe fn new() -> Self {
        let mut __bindgen_tmp = ::std::mem::MaybeUninit::uninit();
        gmx_mtop_t_gmx_mtop_t(__bindgen_tmp.as_mut_ptr());
        __bindgen_tmp.assume_init()
    }
    #[inline]
    pub unsafe fn destruct(&mut self) {
        gmx_mtop_t_gmx_mtop_t_destructor(self)
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct t_topology {
    pub name: *mut *mut ::std::os::raw::c_char,
    pub idef: t_idef,
    pub atoms: t_atoms,
    pub mols: t_block,
    pub bIntermolecularInteractions: bool,
    pub symtab: t_symtab,
}
#[repr(C)]
pub struct TprHelper {
    pub mtop: gmx_mtop_t,
    pub top: t_topology,
    pub state: t_state,
    pub ir: t_inputrec,
}
extern "C" {
    #[link_name = "\u{1}_ZN9TprHelper7get_topEv"]
    pub fn TprHelper_get_top(this: *mut TprHelper) -> *mut t_topology;
}
extern "C" {
    #[link_name = "\u{1}_ZN9TprHelper10get_natomsEv"]
    pub fn TprHelper_get_natoms(this: *mut TprHelper) -> usize;
}
extern "C" {
    #[link_name = "\u{1}_ZN9TprHelper12get_atom_xyzEm"]
    pub fn TprHelper_get_atom_xyz(this: *mut TprHelper, ind: usize) -> *mut f32;
}
extern "C" {
    #[link_name = "\u{1}_ZN9TprHelper7get_boxEv"]
    pub fn TprHelper_get_box(this: *mut TprHelper) -> *mut f32;
}
extern "C" {
    #[link_name = "\u{1}_ZN9TprHelper12get_atomnameEm"]
    pub fn TprHelper_get_atomname(this: *mut TprHelper, ind: usize) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    #[link_name = "\u{1}_ZN9TprHelperC1EPKc"]
    pub fn TprHelper_TprHelper(this: *mut TprHelper, fname: *const ::std::os::raw::c_char);
}
extern "C" {
    #[link_name = "\u{1}_ZN9TprHelperD1Ev"]
    pub fn TprHelper_TprHelper_destructor(this: *mut TprHelper);
}
impl TprHelper {
    #[inline]
    pub unsafe fn get_top(&mut self) -> *mut t_topology {
        TprHelper_get_top(self)
    }
    #[inline]
    pub unsafe fn get_natoms(&mut self) -> usize {
        TprHelper_get_natoms(self)
    }
    #[inline]
    pub unsafe fn get_atom_xyz(&mut self, ind: usize) -> *mut f32 {
        TprHelper_get_atom_xyz(self, ind)
    }
    #[inline]
    pub unsafe fn get_box(&mut self) -> *mut f32 {
        TprHelper_get_box(self)
    }
    #[inline]
    pub unsafe fn get_atomname(&mut self, ind: usize) -> *mut ::std::os::raw::c_char {
        TprHelper_get_atomname(self, ind)
    }
    #[inline]
    pub unsafe fn new(fname: *const ::std::os::raw::c_char) -> Self {
        let mut __bindgen_tmp = ::std::mem::MaybeUninit::uninit();
        TprHelper_TprHelper(__bindgen_tmp.as_mut_ptr(), fname);
        __bindgen_tmp.assume_init()
    }
    #[inline]
    pub unsafe fn destruct(&mut self) {
        TprHelper_TprHelper_destructor(self)
    }
}
