[package]
name = "molar_gromacs"
version.workspace = true
edition.workspace = true
authors.workspace = true
links = "stdc++"

[dependencies]
ascii.workspace = true
anyhow.workspace = true

[build-dependencies]
cmake.workspace = true
#bindgen = "0.66.1"