from __future__ import annotations

import builtins
import datetime
import typing
import numpy as np

# Python binding API. Coordinates and distances use nm; time uses ps.
# Arrays use float32 in pymolar and float64 in pymolar_f64.

class _IsometryTransform:
    """Opaque returned transform; not exported as a package-level class."""
    def __repr__(self) -> builtins.str: ...


class Atom:
    name: builtins.str
    resname: builtins.str
    resid: builtins.int
    atomic_number: builtins.int
    mass: builtins.float
    charge: builtins.float
    type_name: builtins.str | None
    type_id: builtins.int | None
    chain: builtins.str
    bfactor: builtins.float
    occupancy: builtins.float

    def __new__(cls) -> Atom: ...


class _AtomView:
    """Returned mutable topology view; no public package-level constructor."""
    name: builtins.str
    resname: builtins.str
    resid: builtins.int
    atomic_number: builtins.int
    mass: builtins.float
    charge: builtins.float
    type_name: builtins.str | None
    type_id: builtins.int | None
    chain: builtins.str
    bfactor: builtins.float
    occupancy: builtins.float


class Particle:
    @property
    def id(self) -> builtins.int: ...
    pos: np.ndarray
    x: builtins.float
    y: builtins.float
    z: builtins.float
    @property
    def atom(self) -> _AtomView: ...
    name: builtins.str
    resname: builtins.str
    resid: builtins.int
    @property
    def resindex(self) -> builtins.int: ...
    atomic_number: builtins.int
    mass: builtins.float
    charge: builtins.float
    type_name: builtins.str | None
    type_id: builtins.int | None
    chain: builtins.str
    bfactor: builtins.float
    occupancy: builtins.float


class Topology:
    def __len__(self) -> builtins.int: ...


class State:
    box: PeriodicBox
    time: builtins.float

    def __len__(self) -> builtins.int: ...
    def set_box_from(self, arg: System | Sel) -> None: ...


class PeriodicBox:
    @typing.overload
    def __new__(cls, matrix: np.ndarray | list[list[builtins.float]]) -> PeriodicBox: ...
    @typing.overload
    def __new__(cls, vectors: np.ndarray | list[builtins.float], angles: np.ndarray | list[builtins.float]) -> PeriodicBox: ...

    def to_vectors_angles(self) -> tuple[np.ndarray, np.ndarray]: ...
    def shortest_vector(self, arr: np.ndarray | list[builtins.float], dims: list[builtins.bool] | None = None) -> np.ndarray: ...
    def closest_image(self, point: np.ndarray | list[builtins.float], target: np.ndarray | list[builtins.float], dims: list[builtins.bool] | None = None) -> np.ndarray: ...
    def get_matrix(self) -> np.ndarray: ...
    def to_box_coords(self, point: np.ndarray | list[builtins.float]) -> np.ndarray: ...
    def to_lab_coords(self, point: np.ndarray | list[builtins.float]) -> np.ndarray: ...
    def get_box_extents(self) -> np.ndarray: ...
    def get_lab_extents(self) -> np.ndarray: ...
    def is_triclinic(self) -> builtins.bool: ...
    def distance_squared(self, p1: np.ndarray | list[builtins.float], p2: np.ndarray | list[builtins.float], dims: list[builtins.bool]) -> builtins.float: ...
    def distance(self, p1: np.ndarray | list[builtins.float], p2: np.ndarray | list[builtins.float], dims: list[builtins.bool]) -> builtins.float: ...
    def wrap_point(self, p: np.ndarray | list[builtins.float]) -> np.ndarray: ...


class FileStats:
    @property
    def elapsed_time(self) -> datetime.timedelta: ...
    @property
    def frames_processed(self) -> builtins.int: ...
    @property
    def cur_t(self) -> builtins.float: ...

    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...


class FileHandler:
    @property
    def stats(self) -> FileStats: ...
    @property
    def file_name(self) -> builtins.str: ...

    def __new__(cls, fname: builtins.str, mode: builtins.str) -> FileHandler: ...
    def read(self) -> tuple[Topology, State]: ...
    def read_topology(self) -> Topology: ...
    def read_state(self) -> State: ...
    def read_state_pick(self, coords: builtins.bool = True, velocities: builtins.bool = True, forces: builtins.bool = True) -> State: ...
    def write(self, data: System | Sel | tuple[Topology, State]) -> None: ...
    def write_topology(self, data: System | Sel | Topology) -> None: ...
    def write_state(self, data: System | Sel | State) -> None: ...
    def __iter__(self) -> FileHandler: ...
    def __next__(self) -> State: ...
    def __enter__(self) -> FileHandler: ...
    def __exit__(self, exc_type: typing.Any, exc_val: typing.Any, exc_tb: typing.Any) -> builtins.bool: ...
    def skip_to_last(self) -> None: ...
    def write_state_pick(self, data: System | Sel | State, coords: builtins.bool = True, velocities: builtins.bool = True, forces: builtins.bool = True) -> None: ...
    def skip_to_frame(self, fr: builtins.int) -> None: ...
    def skip_to_time(self, t: builtins.float) -> None: ...


class System:
    """Coupled topology/frame. __call__ tuple ranges exclude the end."""
    state: State
    topology: Topology
    time: builtins.float
    box: PeriodicBox

    @typing.overload
    def __new__(cls) -> System: ...
    @typing.overload
    def __new__(cls, fname: builtins.str) -> System: ...
    @typing.overload
    def __new__(cls, topology: Topology, state: State) -> System: ...

    def __len__(self) -> builtins.int: ...
    def __call__(self, arg: builtins.str | tuple[builtins.int, builtins.int] | list[builtins.int] | None = None) -> Sel: ...
    def replace_state_deep(self, st: State) -> None: ...
    def save(self, fname: builtins.str) -> None: ...
    def apply_ff(self, ff: builtins.str = "gaff") -> None: ...
    def apply_charges(self, model: builtins.str = "espaloma") -> None: ...
    def perceive_connectivity(self, tolerance: builtins.float = 0.045, min_distance: builtins.float = 0.04, pbc: builtins.bool = False) -> builtins.int: ...
    def perceive_bond_orders(self, infer_hydrogens: builtins.bool = False, total_charge: builtins.int | None = None) -> list[builtins.str]: ...
    def add_hydrogens(self) -> builtins.int: ...
    def prepare_for_ff(self, infer_hydrogens: builtins.bool = False, add_hydrogens: builtins.bool = False, total_charge: builtins.int | None = None) -> None: ...
    def remove(self, arg: Sel | builtins.str | tuple[builtins.int, builtins.int] | list[builtins.int]) -> None: ...
    @typing.overload
    def append(self, arg: Sel | builtins.str | tuple[builtins.int, builtins.int] | list[builtins.int]) -> None: ...
    @typing.overload
    def append(self, atom: Atom | _AtomView, pos: np.ndarray | list[builtins.float]) -> None: ...
    def set_box_from(self, src: System | Sel) -> None: ...
    def __getitem__(self, i: builtins.int) -> Particle: ...
    def __iter__(self) -> SysParticleIterator: ...
    def iter_pos(self) -> SysPosIterator: ...
    def iter_atoms(self) -> SysAtomIterator: ...


class Sel:
    """Sorted indices with shared topology/state. coords is a (3, n) copy."""
    @property
    def index(self) -> np.ndarray: ...
    coords: np.ndarray
    system: System
    state: State
    topology: Topology
    time: builtins.float
    box: PeriodicBox

    def __len__(self) -> builtins.int: ...
    def __call__(self, arg: builtins.str | tuple[builtins.int, builtins.int] | list[builtins.int]) -> Sel:
        """Tuple ranges include the end; lists contain local indices."""
        ...
    def __getitem__(self, i: builtins.int) -> Particle: ...
    def __iter__(self) -> typing.Iterator[Particle]: ...
    def replace_state_deep(self, st: State) -> None: ...
    def set_same_chain(self, val: builtins.str) -> None: ...
    def set_same_resname(self, val: builtins.str) -> None: ...
    def set_same_resid(self, val: builtins.int) -> None: ...
    def set_same_name(self, val: builtins.str) -> None: ...
    def set_same_mass(self, val: builtins.float) -> None: ...
    def set_same_bfactor(self, val: builtins.float) -> None: ...
    def set_box_from(self, sys: System) -> None: ...
    def com(self, dims: list[builtins.bool] | None = None) -> np.ndarray: ...
    def cog(self, dims: list[builtins.bool] | None = None) -> np.ndarray: ...
    def principal_transform(self, pbc: builtins.bool = False) -> _IsometryTransform: ...
    def apply_transform(self, tr: _IsometryTransform) -> None: ...
    def gyration(self, pbc: builtins.bool = False) -> builtins.float: ...
    def min_max(self) -> tuple[np.ndarray, np.ndarray]: ...
    def inertia(self, pbc: builtins.bool = False) -> tuple[np.ndarray, np.ndarray]: ...
    def save(self, fname: builtins.str) -> None: ...
    def translate(self, arg: np.ndarray | list[builtins.float]) -> None: ...
    def unwrap_simple(self) -> None: ...
    def whole_residues(self) -> Sel: ...
    def whole_chains(self) -> Sel: ...
    def apply_ff(self, ff: builtins.str = "gaff") -> None: ...
    def apply_charges(self, model: builtins.str = "espaloma") -> None: ...
    def dssp(self) -> list[builtins.str]: ...
    def dssp_string(self) -> builtins.str: ...
    def ss(self, algo: builtins.str = "dssp") -> list[builtins.str]: ...
    def ss_string(self, algo: builtins.str = "dssp") -> builtins.str: ...
    def __contains__(self, idx: builtins.int) -> builtins.bool: ...
    def __or__(self, other: Sel) -> Sel: ...
    def __and__(self, other: Sel) -> Sel: ...
    def __sub__(self, other: Sel) -> Sel: ...
    def __invert__(self) -> Sel: ...
    def split_resindex(self) -> list[Sel]: ...
    def split_chain(self) -> list[Sel]: ...
    def split_molecule(self) -> list[Sel]: ...
    def to_gromacs_ndx(self, name: builtins.str) -> builtins.str: ...
    def iter_pos(self) -> SelPosIterator: ...
    def iter_atoms(self) -> SelAtomIterator: ...


class Sasa:
    """Exported result type; no constructor or calculator is exposed in Python."""
    @property
    def areas(self) -> list[builtins.float]: ...
    @property
    def volumes(self) -> list[builtins.float]: ...
    @property
    def total_area(self) -> builtins.float: ...
    @property
    def total_volume(self) -> builtins.float: ...


class NdxFile:
    def __new__(cls, fname: builtins.str) -> NdxFile: ...
    def get_group_as_sel(self, gr_name: builtins.str, sys: System) -> Sel: ...


class SysPosIterator:
    def __iter__(self) -> SysPosIterator: ...
    def __next__(self) -> np.ndarray: ...


class SysAtomIterator:
    def __iter__(self) -> SysAtomIterator: ...
    def __next__(self) -> _AtomView: ...


class SelPosIterator:
    def __iter__(self) -> SelPosIterator: ...
    def __next__(self) -> np.ndarray: ...


class SelAtomIterator:
    def __iter__(self) -> SelAtomIterator: ...
    def __next__(self) -> _AtomView: ...


class SysParticleIterator:
    def __iter__(self) -> SysParticleIterator: ...
    def __next__(self) -> Particle: ...


def greeting() -> None: ...
def fit_transform(sel1: Sel, sel2: Sel) -> _IsometryTransform: ...
def fit_transform_matching(sel1: Sel, sel2: Sel) -> _IsometryTransform: ...
def rmsd_py(sel1: Sel, sel2: Sel) -> builtins.float: ...
def rmsd_mw(sel1: Sel, sel2: Sel) -> builtins.float: ...
def distance_search(
    cutoff: builtins.float | builtins.str,
    data1: Sel,
    data2: Sel | None = None,
    dims: list[builtins.bool] | None = None,
) -> tuple[np.ndarray, np.ndarray]: ...
